# Info
site_name: Meetix - Ambulance
site_url: 'https://ambu.meetix.nl/'
site_description: 'Meetix Ambulance'
site_author: 'MeetixMedia'

# Repo
repo_url: 'https://github.com/MeetixRP/Meetix-Ambulance'
repo_name: 'MeetixRP/Meetix-Ambulance'
edit_uri: 'https://github.com/MeetixRP/Meetix-Ambulance/tree/main/docs'

# Copyright
copyright: Copyright &copy; 2019 - 2023 Meetix



#Config
site_name: Meetix Ambulance
theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Donkere modus
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: ichte modus
#Navigeer
nav:
  - Welkom: index.md
  - Regels:
    - Parkeerbeleid: parkeerbeleid.md
  - Rooster: rooster.md
  - Sollicitatie: sollicitatie.md
  - Klachten: klachten.md
  - Ziekenhuis: ziekenhuis.md
  - Rangen informatie:
    - Rangen: rangen.md
    - Specialisaties en trainingen: specialisaties.md
  - Uitrusting:
    - Voertuigen: voertuigen.md
    - Hulpmiddelen: hulpmiddelen.md
    - Medicatie: medicatie.md
  - Basis informatie (Ambu):
    - Stappenplan: stappenplan.md
    - Communicatie: communicatie.md
    - Promoties: promoties.md
    - Medisch menu: medischmenu.md
  - Extra verdieping (Ambu):
    - ABCDE Model: abcdemodel.md
    - Specialisaties:
      - S.O.R.T: sort.md
      - MMT: mmt.md
      - OVD-G: ovdg.md
# Extensions

markdown_extensions:
  - pymdownx.keys
